version: "2"
services:
  node:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "8081:8081"
    command: "npm start"
