version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
      - run: npm audit --audit-level=moderate
      - run: npm test
      - run: npm run graphql:validate
workflows:
  build-and-test:
    jobs:
      - build-and-test
