# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'AudioVerse' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'Firebase/Core', :modular_headers => true
  pod 'FBSDKCoreKit', :modular_headers => true
  pod 'FBSDKLoginKit'

  target 'AudioVerseTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

   # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'AudioVerse-tvOS' do
  # Pods for AudioVerse-tvOS

  target 'AudioVerse-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
